// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feature/featurepb/feature.proto

package featurepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Feature struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Operation            string   `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	Delta                string   `protobuf:"bytes,5,opt,name=delta,proto3" json:"delta,omitempty"`
	Timestamp            string   `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_95200eb8bb5a3731, []int{0}
}

func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (m *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(m, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Feature) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Feature) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *Feature) GetDelta() string {
	if m != nil {
		return m.Delta
	}
	return ""
}

func (m *Feature) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type Document struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	User                 string   `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_95200eb8bb5a3731, []int{1}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Document) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Document) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Document) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Document) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type DocumentRequest struct {
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DocumentRequest) Reset()         { *m = DocumentRequest{} }
func (m *DocumentRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentRequest) ProtoMessage()    {}
func (*DocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95200eb8bb5a3731, []int{2}
}

func (m *DocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentRequest.Unmarshal(m, b)
}
func (m *DocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentRequest.Marshal(b, m, deterministic)
}
func (m *DocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentRequest.Merge(m, src)
}
func (m *DocumentRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentRequest.Size(m)
}
func (m *DocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentRequest proto.InternalMessageInfo

func (m *DocumentRequest) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type DocumentResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentResponse) Reset()         { *m = DocumentResponse{} }
func (m *DocumentResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentResponse) ProtoMessage()    {}
func (*DocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95200eb8bb5a3731, []int{3}
}

func (m *DocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentResponse.Unmarshal(m, b)
}
func (m *DocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentResponse.Marshal(b, m, deterministic)
}
func (m *DocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentResponse.Merge(m, src)
}
func (m *DocumentResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentResponse.Size(m)
}
func (m *DocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentResponse proto.InternalMessageInfo

func (m *DocumentResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type FeatureRequest struct {
	Feature              *Feature `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureRequest) Reset()         { *m = FeatureRequest{} }
func (m *FeatureRequest) String() string { return proto.CompactTextString(m) }
func (*FeatureRequest) ProtoMessage()    {}
func (*FeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95200eb8bb5a3731, []int{4}
}

func (m *FeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureRequest.Unmarshal(m, b)
}
func (m *FeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureRequest.Marshal(b, m, deterministic)
}
func (m *FeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureRequest.Merge(m, src)
}
func (m *FeatureRequest) XXX_Size() int {
	return xxx_messageInfo_FeatureRequest.Size(m)
}
func (m *FeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureRequest proto.InternalMessageInfo

func (m *FeatureRequest) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

type FeatureResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureResponse) Reset()         { *m = FeatureResponse{} }
func (m *FeatureResponse) String() string { return proto.CompactTextString(m) }
func (*FeatureResponse) ProtoMessage()    {}
func (*FeatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95200eb8bb5a3731, []int{5}
}

func (m *FeatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureResponse.Unmarshal(m, b)
}
func (m *FeatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureResponse.Marshal(b, m, deterministic)
}
func (m *FeatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureResponse.Merge(m, src)
}
func (m *FeatureResponse) XXX_Size() int {
	return xxx_messageInfo_FeatureResponse.Size(m)
}
func (m *FeatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureResponse proto.InternalMessageInfo

func (m *FeatureResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type LongFeatureRequest struct {
	Feature              *Feature `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongFeatureRequest) Reset()         { *m = LongFeatureRequest{} }
func (m *LongFeatureRequest) String() string { return proto.CompactTextString(m) }
func (*LongFeatureRequest) ProtoMessage()    {}
func (*LongFeatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95200eb8bb5a3731, []int{6}
}

func (m *LongFeatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongFeatureRequest.Unmarshal(m, b)
}
func (m *LongFeatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongFeatureRequest.Marshal(b, m, deterministic)
}
func (m *LongFeatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongFeatureRequest.Merge(m, src)
}
func (m *LongFeatureRequest) XXX_Size() int {
	return xxx_messageInfo_LongFeatureRequest.Size(m)
}
func (m *LongFeatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongFeatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongFeatureRequest proto.InternalMessageInfo

func (m *LongFeatureRequest) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

type LongFeatureResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongFeatureResponse) Reset()         { *m = LongFeatureResponse{} }
func (m *LongFeatureResponse) String() string { return proto.CompactTextString(m) }
func (*LongFeatureResponse) ProtoMessage()    {}
func (*LongFeatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95200eb8bb5a3731, []int{7}
}

func (m *LongFeatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongFeatureResponse.Unmarshal(m, b)
}
func (m *LongFeatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongFeatureResponse.Marshal(b, m, deterministic)
}
func (m *LongFeatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongFeatureResponse.Merge(m, src)
}
func (m *LongFeatureResponse) XXX_Size() int {
	return xxx_messageInfo_LongFeatureResponse.Size(m)
}
func (m *LongFeatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongFeatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongFeatureResponse proto.InternalMessageInfo

func (m *LongFeatureResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Feature)(nil), "feature.Feature")
	proto.RegisterType((*Document)(nil), "feature.Document")
	proto.RegisterType((*DocumentRequest)(nil), "feature.DocumentRequest")
	proto.RegisterType((*DocumentResponse)(nil), "feature.DocumentResponse")
	proto.RegisterType((*FeatureRequest)(nil), "feature.FeatureRequest")
	proto.RegisterType((*FeatureResponse)(nil), "feature.FeatureResponse")
	proto.RegisterType((*LongFeatureRequest)(nil), "feature.LongFeatureRequest")
	proto.RegisterType((*LongFeatureResponse)(nil), "feature.LongFeatureResponse")
}

func init() { proto.RegisterFile("feature/featurepb/feature.proto", fileDescriptor_95200eb8bb5a3731) }

var fileDescriptor_95200eb8bb5a3731 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4b, 0x4f, 0xf2, 0x40,
	0x14, 0xfd, 0xca, 0x9b, 0x4b, 0x02, 0x7c, 0xa3, 0xd1, 0x11, 0x49, 0x34, 0x5d, 0x21, 0x09, 0x98,
	0xe0, 0xd6, 0x05, 0xf1, 0xb9, 0x71, 0x05, 0x71, 0xe3, 0x6e, 0xa0, 0x57, 0xd3, 0x84, 0x76, 0x6a,
	0x67, 0xea, 0xc2, 0x7f, 0xe2, 0x0f, 0x75, 0x6f, 0x3a, 0xaf, 0x8a, 0x25, 0x71, 0xe1, 0x6a, 0xee,
	0xf3, 0x9c, 0x73, 0xef, 0xcd, 0xc0, 0xc9, 0x33, 0x32, 0x99, 0xa5, 0x78, 0x6e, 0xde, 0x64, 0x65,
	0xad, 0x69, 0x92, 0x72, 0xc9, 0x49, 0xd3, 0xb8, 0xfe, 0x87, 0x07, 0xcd, 0x3b, 0x6d, 0x13, 0x02,
	0xb5, 0x98, 0x45, 0x48, 0xbd, 0x53, 0x6f, 0xd4, 0x5e, 0x28, 0x9b, 0xec, 0x43, 0x5d, 0xf2, 0x24,
	0x5c, 0xd3, 0x8a, 0x0a, 0x6a, 0x27, 0xaf, 0xcc, 0x04, 0xa6, 0xb4, 0xaa, 0x2b, 0x73, 0x9b, 0x0c,
	0xa1, 0xcd, 0x13, 0x4c, 0x99, 0x0c, 0x79, 0x4c, 0x6b, 0x2a, 0x51, 0x04, 0x72, 0x9c, 0x00, 0x37,
	0x92, 0xd1, 0xba, 0xc6, 0x51, 0x4e, 0xde, 0x23, 0xc3, 0x08, 0x85, 0x64, 0x51, 0x42, 0x1b, 0xba,
	0xc7, 0x05, 0xfc, 0x77, 0x68, 0xdd, 0xf0, 0x75, 0x16, 0x61, 0x2c, 0x15, 0x63, 0x16, 0x06, 0x56,
	0x5b, 0x6e, 0x3b, 0xbd, 0x95, 0x5d, 0x7a, 0xab, 0xdf, 0xf5, 0x6e, 0xf1, 0xd4, 0x7e, 0xf0, 0xb8,
	0x69, 0xea, 0xc5, 0x34, 0xfe, 0x1c, 0x7a, 0x96, 0x7b, 0x81, 0xaf, 0x19, 0x0a, 0x49, 0x26, 0xd0,
	0x0a, 0x4c, 0x48, 0xc9, 0xe8, 0xcc, 0xfe, 0x4f, 0xed, 0x56, 0x5d, 0xad, 0x2b, 0xf1, 0xc7, 0xd0,
	0x2f, 0x10, 0x44, 0xc2, 0x63, 0x81, 0xe4, 0x00, 0x1a, 0x29, 0x8a, 0x6c, 0x23, 0xcd, 0x1c, 0xc6,
	0xf3, 0x2f, 0xa1, 0x6b, 0x8e, 0x60, 0xc9, 0xc6, 0x60, 0x4f, 0x64, 0xb8, 0xfa, 0x8e, 0xcb, 0x56,
	0xba, 0x1b, 0x9e, 0x41, 0xcf, 0x75, 0xff, 0x42, 0x34, 0x07, 0xf2, 0xc0, 0xe3, 0x97, 0x3f, 0x90,
	0x4d, 0x60, 0x6f, 0x0b, 0xa1, 0x20, 0x14, 0x92, 0xc9, 0x4c, 0x58, 0x42, 0xed, 0xcd, 0x3e, 0x3d,
	0x37, 0xda, 0x12, 0xd3, 0xb7, 0x70, 0x8d, 0xe4, 0x1e, 0xba, 0xd7, 0x29, 0x32, 0x89, 0xee, 0xb8,
	0xb4, 0xbc, 0x47, 0xad, 0x6c, 0x70, 0xb4, 0x23, 0xa3, 0x19, 0xfd, 0x7f, 0xe4, 0xd6, 0x41, 0x3f,
	0x26, 0x01, 0x93, 0x28, 0xc8, 0x61, 0x49, 0xb7, 0xc1, 0xa1, 0xe5, 0x84, 0x83, 0x59, 0x6e, 0xed,
	0xc4, 0x42, 0x1d, 0xbb, 0x8e, 0xf2, 0xc2, 0x06, 0xc3, 0xdd, 0x49, 0x0b, 0x39, 0xf2, 0xae, 0x3a,
	0x4f, 0x6d, 0xf7, 0xf7, 0x56, 0x0d, 0xf5, 0xe9, 0x2e, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x15,
	0xc3, 0x49, 0xb5, 0x97, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeatureServiceClient is the client API for FeatureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeatureServiceClient interface {
	// Create Document Unary API
	CreateDocument(ctx context.Context, in *DocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	// Unary API
	FeatureUpdates(ctx context.Context, in *FeatureRequest, opts ...grpc.CallOption) (*FeatureResponse, error)
	// Client Streaming
	LongFeatureUpdates(ctx context.Context, opts ...grpc.CallOption) (FeatureService_LongFeatureUpdatesClient, error)
}

type featureServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeatureServiceClient(cc *grpc.ClientConn) FeatureServiceClient {
	return &featureServiceClient{cc}
}

func (c *featureServiceClient) CreateDocument(ctx context.Context, in *DocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, "/feature.FeatureService/CreateDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) FeatureUpdates(ctx context.Context, in *FeatureRequest, opts ...grpc.CallOption) (*FeatureResponse, error) {
	out := new(FeatureResponse)
	err := c.cc.Invoke(ctx, "/feature.FeatureService/FeatureUpdates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureServiceClient) LongFeatureUpdates(ctx context.Context, opts ...grpc.CallOption) (FeatureService_LongFeatureUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FeatureService_serviceDesc.Streams[0], "/feature.FeatureService/LongFeatureUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &featureServiceLongFeatureUpdatesClient{stream}
	return x, nil
}

type FeatureService_LongFeatureUpdatesClient interface {
	Send(*LongFeatureRequest) error
	CloseAndRecv() (*LongFeatureResponse, error)
	grpc.ClientStream
}

type featureServiceLongFeatureUpdatesClient struct {
	grpc.ClientStream
}

func (x *featureServiceLongFeatureUpdatesClient) Send(m *LongFeatureRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *featureServiceLongFeatureUpdatesClient) CloseAndRecv() (*LongFeatureResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LongFeatureResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FeatureServiceServer is the server API for FeatureService service.
type FeatureServiceServer interface {
	// Create Document Unary API
	CreateDocument(context.Context, *DocumentRequest) (*DocumentResponse, error)
	// Unary API
	FeatureUpdates(context.Context, *FeatureRequest) (*FeatureResponse, error)
	// Client Streaming
	LongFeatureUpdates(FeatureService_LongFeatureUpdatesServer) error
}

func RegisterFeatureServiceServer(s *grpc.Server, srv FeatureServiceServer) {
	s.RegisterService(&_FeatureService_serviceDesc, srv)
}

func _FeatureService_CreateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).CreateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feature.FeatureService/CreateDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).CreateDocument(ctx, req.(*DocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_FeatureUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureServiceServer).FeatureUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feature.FeatureService/FeatureUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureServiceServer).FeatureUpdates(ctx, req.(*FeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureService_LongFeatureUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FeatureServiceServer).LongFeatureUpdates(&featureServiceLongFeatureUpdatesServer{stream})
}

type FeatureService_LongFeatureUpdatesServer interface {
	SendAndClose(*LongFeatureResponse) error
	Recv() (*LongFeatureRequest, error)
	grpc.ServerStream
}

type featureServiceLongFeatureUpdatesServer struct {
	grpc.ServerStream
}

func (x *featureServiceLongFeatureUpdatesServer) SendAndClose(m *LongFeatureResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *featureServiceLongFeatureUpdatesServer) Recv() (*LongFeatureRequest, error) {
	m := new(LongFeatureRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FeatureService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feature.FeatureService",
	HandlerType: (*FeatureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDocument",
			Handler:    _FeatureService_CreateDocument_Handler,
		},
		{
			MethodName: "FeatureUpdates",
			Handler:    _FeatureService_FeatureUpdates_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LongFeatureUpdates",
			Handler:       _FeatureService_LongFeatureUpdates_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "feature/featurepb/feature.proto",
}
